services:
  fastapi:
    image: goegoe0212/fastapi-kubernetes
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - title=FastAPIのテストAPI
      - description=My App Description
      - version=0.1.0
      - openapi_url=/openapi.json
      - docs_url=/docs
      - prefix_url=/test
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - "8000:8000"
    depends_on:
      - redis-service
  
  redis-service:
    image: redis:alpine
    environment:
      - TZ=Asia/Tokyo