services:
  fastapi:
    image: fastapi-docker:develop
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    environment:
      - title=FastAPIのテストAPI
      - description=My App Description
      - version=0.1.0
      - openapi_url=/openapi.json
      - docs_url=/docs
      - prefix_url=/test
    tty: true
    stdin_open: true
    command: /bin/bash
    depends_on:
      - redis

  redis:
    image: redis:alpine
    environment:
      - TZ=Asia/Tokyo