services:
  fastapi:
    image: goegoe0212/fastapi-kubernetes:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - "80:80"